### ISSUE TITLE
我想问下Mock模拟分页数据的问题。

### ISSUE THREAD

**Issue by waney** [molysama/vue-learn#3]
Mock.mock(n.path, n.data)
这里的path怎么解决动态参数问题，比如分页码，在数据里能接收到这个参数吗

**Comment by molysama** [comment]
分页码之类的参数一般都是放在data里的，你需要的大概是 https://github.com/nuysoft/Mock/wiki

**Comment by waney** [comment]
我就是不太明白如何模拟分页数据。比如取1-10条，第二页为11-20条，列表里的ID能按顺序。

**Comment by molysama** [comment]
最简单的就是直接加匹配项啊，没啥好纠结的。
比如: 
/page?pageNumber=1
/page?pageNumber=2
...
各自响应不同的请求就行了，你需要了解的是Mock的用法

**Comment by waney** [comment]
我试了还是达不到效果，比如点第一页，列出1-10，第二页列出10-19，再点回第一页出来的却是11-20
我是按照你的方式两个path
export const activitiesAll1 = 'activities?page=1'
export const activitiesAll2 = 'activities?page=2'


export const activities = [
  {
    path: API.activitiesAll1,
    data: {'list|10': [{
      'id|+1': 1,
      'title': '@CTITLE',
      'start': '@DATE @TIME',
      'stop': '@DATE @TIME',
      'address|+1': ['温州市鹿城区少年活动中心', '温州大剧院', '温州万象城巨幕厅'],
      'status|+1': [0, 1, 2, 1, 1, 1]
    }]}
  },
  {
    path: API.activitiesAll2,
    data: {'list|10': [{
      'id|+1': 10,
      'title': '@CTITLE',
      'start': '@DATE @TIME',
      'stop': '@DATE @TIME',
      'address|+1': ['温州市鹿城区少年活动中心', '温州大剧院', '温州万象城巨幕厅'],
      'status|+1': [0, 1, 2, 1, 1, 1]
    }]}
  },

**Comment by molysama** [comment]
你Mock使用方法不对，而且mock只是模拟数据而已，不要纠结在这种地方
